[2022-12-17 05:32:10,148] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: scheduler_dag.data_generator_task manual__2022-12-17T05:32:03.357108+00:00 [queued]>
[2022-12-17 05:32:10,195] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: scheduler_dag.data_generator_task manual__2022-12-17T05:32:03.357108+00:00 [queued]>
[2022-12-17 05:32:10,197] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-17 05:32:10,198] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-12-17 05:32:10,200] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-17 05:32:10,245] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): data_generator_task> on 2022-12-17 05:32:03.357108+00:00
[2022-12-17 05:32:10,251] {standard_task_runner.py:52} INFO - Started process 260 to run task
[2022-12-17 05:32:10,267] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'scheduler_dag', 'data_generator_task', 'manual__2022-12-17T05:32:03.357108+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/scheduler.py', '--cfg-path', '/tmp/tmpy4rjvehu', '--error-file', '/tmp/tmp_bmt5yez']
[2022-12-17 05:32:10,269] {standard_task_runner.py:77} INFO - Job 5: Subtask data_generator_task
[2022-12-17 05:32:10,427] {logging_mixin.py:109} INFO - Running <TaskInstance: scheduler_dag.data_generator_task manual__2022-12-17T05:32:03.357108+00:00 [running]> on host 74d73c162c9e
[2022-12-17 05:32:10,593] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=scheduler_dag
AIRFLOW_CTX_TASK_ID=data_generator_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-17T05:32:03.357108+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-17T05:32:03.357108+00:00
[2022-12-17 05:32:10,597] {python.py:175} INFO - Done. Returned value was: None
[2022-12-17 05:32:10,632] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=scheduler_dag, task_id=data_generator_task, execution_date=20221217T053203, start_date=20221217T053210, end_date=20221217T053210
[2022-12-17 05:32:10,718] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-12-17 05:32:10,876] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
